name: Lint On Scripts
#
# Run ShellCheck on all scripts and generates report as build artefact
#

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    
jobs:

  Compile:

#    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/os/.github/workflows/complete-artifact-matrix-all.yml@main
